services:
  smith-ai:
    image: smith/python3.12/ai
    restart: no
    volumes:
      - ../app:/opt/app:delegated
    ports:
      - "4444:8080"
    working_dir: /opt/app
    command: python web/app.py
    environment:
      - PYTHONUNBUFFERED=1