services:
  smith-ai:
    image: smith/python3.12/ai
    command: python -u /opt/app/main.py
    restart: no
    volumes:
      - ../app:/opt/app:delegated
    working_dir: /opt/app
    # ports:
    #   - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1

# volumes:
#   db:
#     driver: local